config/routes.rb
Rails.application.routes.draw do

  # Resources
  resources :images, only: [:new, :create, :destroy]
  resources :articles do
    get 'published', on: :collection #view and scope
    put 'unpublish', on: :member # action
    post 'publish', on: :member # action
    get 'prepare_publish', on: :member # set tags and release date
  end

  # Devise
  devise_for :users

  as :user do
    get '/auth/login'          => "devise/sessions#new", as: :login
    post '/auth/login'          => "devise/sessions#create"
    get '/auth/logout'         => "devise/sessions#destroy", as: :logout
    get '/auth/reset_password' => "devise/passwords#new", as: :reset_password
    post '/auth/reset_password' => "devise/passwords#create"
    get '/auth/unlock_account' => "devise/unlocks#new", as: :unlock_account
    post '/auth/unlock_account' => "devise/unlocks#create"
  end

  authenticated :user do
    root to: 'articles#index', as: :authenticated_root
  end

  # App root
  root to: redirect('/auth/login')

end

app/models/article.rb
class Article < ActiveRecord::Base

	# Includes
	extend FriendlyId
	acts_as_taggable

	# Pretty URLs
	friendly_id :title, use: :slugged

	# Relationships
	belongs_to :user

	# Validations
	validates :title, :content, :user_id, :description,
		presence: true

	validates :title,
		uniqueness: true

	validates :published,
		inclusion: { in: [true, false] }

	validates :tag_list, :published_at,
		presence: false,
		allow_blank: true

	validates :preview_image_url,
		format: { with: /https?:\/\/[\S]+/, message: "is not a valid URL" },
		allow_blank: true

	validates :description,
		length: { maximum: 425 },
		allow_blank: true

	# Search
	searchable do
	  text :title, boost: 5
	  text :content, boost: 3
   	text :tag_list, boost: 1
	  boolean :published
	  time :updated_at
	  time :published_at
	end

	# Scopes
	scope :unpublished, -> { where(published: false) }
	scope :published, -> { where(published: true) }

	# Methods
	def should_generate_new_friendly_id?
	  title_changed?
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :publish, :prepare_publish, :unpublish, :destroy]

  # GET /articles
  def index
    @search = Article.includes(:user, :tag_list).search do
      fulltext params[:search]

      with :published, false
      order_by :updated_at, :desc
      paginate :page => params[:page], :per_page => 25
    end
    @articles = @search.results
  end

  # GET /published
  def published
    @search = Article.includes(:user, :tag_list).search do
      fulltext params[:search]

      with :published, true
      order_by :updated_at, :desc
      paginate :page => params[:page], :per_page => 25
    end
    @articles = @search.results
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_url, notice: 'Article created.'
    else
      render :edit
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      if params[:commit] === 'Save'
        redirect_to edit_article_path, notice: 'Article saved.'
      elsif params[:commit] === 'Save & Close'
        redirect_to articles_path, notice: 'Article updated.'
      end
    else
      render :edit
    end
  end

  # PUT /articles/1/publish
  def publish
    if @article.save
      if params[:article][:published_at].blank? || params[:article][:tag_list].blank?
        redirect_to prepare_publish_article_url(@article), alert: "Tags and Release Date cannot be blank."
      else
        @article.update!(
          tag_list: params[:article][:tag_list],
          published_at: DateTime.strptime(params[:article][:published_at],'%m-%d-%Y %H:%M %z'), 
          published: true
        )
        redirect_to published_articles_url, notice: 'Article published.'
      end
    else
      redirect_to articles_url, alert: "Article could not be published."
    end
  end

  # PUT /articles/1/prepare_publish
  def prepare_publish
  end

  # PUT /articles/1/unpublish
  def unpublish
    @article.update!(published_at: nil, tag_list: nil, published: false)

    if @article.save
      redirect_to articles_url, notice: 'Article unpublished.'
    else
      redirect_to published_articles_url, alert: "Article could not be unpublished."
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :preview_image_url, :description, :content, :user_id, :published, :published_at, :slug, :tag_list)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper

	# true if published date has passed
	def is_live(publish_date)
		if publish_date > Time.now
			"not-live"
		end
	end

end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div class="panel panel-default border-danger">
      <div class="panel-heading background-color-danger"><%= pluralize(@article.errors.count, "error") %>:</div>
      <div class="panel-body">
        <ul class="list-unstyled">
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, autofocus: true, error: false, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :preview_image_url, 'Preview Image' %>
    <%= f.input :preview_image_url, error: false, label: false, placeholder: 'https://s3_path', input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.input :user_id, as: :hidden, error: false, input_html: { value: current_user.id } %>
  </div>

  <div class="form-group">
    <%= f.input :description, error: false, input_html: { id: "description", class: "form-control" } %>
  </div>
  <div class="char-count hidden"></div>

  <div class="form-group">
    <%= f.label 'Content' %>
    <%= render partial: "shared/editor_tags" %>
    <%= f.input :content, label: false, error: false, input_html: { rows: 14, class: "form-control" } %>
  </div>

  <% unless action_name === 'new' || (action_name === 'edit' && @article.published === false) %>
    <div class="form-group">
      <%= f.label 'Tags' %>
      <%= f.input :tag_list, label: false, error: false, placeholder: "Separate by comma", input_html: { class: "form-control" } %>
    </div>
  <% end %>

  <div class="form-group">
    <div><%= f.label 'Status' %></div>
    <span class="radio">
      <% if action_name === 'new' %>
        <%= f.collection_radio_buttons :published, [[false, 'Draft']], :first, :last, checked: false, error: false, label: false %>
      <% elsif @article.published === true %>
        <%= f.collection_radio_buttons :published, [[true, 'Published']], :first, :last, error: false, label: false %>
      <% else %>
        <%= f.collection_radio_buttons :published, [[false, 'Draft']], :first, :last, checked: false, error: false, label: false %>
      <% end %>
    </span>
  </div>

  <% if @article.published_at %>
    <div class="form-group">
      <%= f.label :published_at, 'Publish Date' %>
      <%= f.input :published_at, as: :string, label: false, error: false, disabled: true, input_html: { id: "publish-date", class: "form-control" } %>
    </div>
  <% end %>

  <hr />

  <div class="form-group">
    <ul class="list-unstyled list-inline">
      <li><%= f.button :submit, "Save", class: "btn btn-default" %></li>
      <% if action_name === 'edit' || @article.errors.any? %>
        <li><%= f.button :submit, "Save & Close", class: "btn btn-default" %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% title "Edit - #{@article.title}" %>

<h1>Edit Article</h1><br />

<%= render 'form' %>

app/views/articles/index.html.erb
<% title "Drafts" %>

<h1 data-no-turbolink>
  Drafts
  <%= link_to 'Create', new_article_path, class: 'btn btn-default pull-right' %>
</h1>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Updated</th>
        <th id="article-actions-draft"></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td data-no-turbolink><%= link_to article.title, article %></td>
          <td><%= article.user.full_name %></td>
          <td><%= article.updated_at.strftime('%m-%d-%Y %I:%M%P') %></td>
          <td>
            <ul class="list-unstyled list-inline">
              <li data-no-turbolink><%= link_to 'Edit', edit_article_path(article) %></li>
              <li><%= link_to 'Destroy', article, method: :delete, data: { confirm: "Delete: #{article.title}" } %></li>
              <li data-no-turbolink><%= link_to 'Publish', prepare_publish_article_path(article) %></li>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= "No draft articles matching your search were found." if @articles.count === 0 %>

<%= paginate @articles %>

app/views/articles/new.html.erb
<% title "Create Article" %>

<h1>Create Article</h1><br />

<%= render 'form' %>

app/views/articles/prepare_publish.html.erb
<% title "Tags & Release Date" %>

<h3 class="title"><%= @article.title %></h3>

<%= simple_form_for @article, url: publish_article_path, html: {method: :post} do |f| %>
  <% if @article.errors.any? %>
    <div class="panel panel-default border-danger">
      <div class="panel-heading background-color-danger"><%= pluralize(@article.errors.count, "error") %>:</div>
      <div class="panel-body">
        <ul class="list-unstyled">
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Tags' %>
    <%= f.input :tag_list, label: false, error: false, placeholder: "Separate by comma", input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :published_at, 'Release Date' %>
    <%= f.input :published_at, as: :string, label: false, error: false, input_html: { id: "publish-date", class: "form-control" } %>
  </div>

  <hr />

  <div class="form-group">
    <%= f.button :submit, "Publish", data: { confirm: "Publish: #{@article.title}" }, class: "btn btn-default" %>
  </div>
<% end %>

app/views/articles/published.html.erb
<% title "Published" %>

<h1 data-no-turbolink>
  Published
  <%= link_to 'Create', new_article_path, class: 'btn btn-default pull-right' %>
</h1>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Tags</th>
        <th>Published</th>
        <th id="article-actions-published"></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td data-no-turbolink><%= link_to article.title, article %></td>
          <td><%= article.user.full_name %></td>
          <td><%= article.tag_list.map { |t| t.titleize }.join(', ') %></td>
          <td class="<%= is_live(article.published_at) %>"><%= article.published_at.strftime('%m-%d-%Y %I:%M%P') %></td>
          <td>
            <ul class="list-unstyled list-inline">
              <li data-no-turbolink><%= link_to 'Revise', edit_article_path(article) %></li>
              <li><%= link_to 'Unpublish', unpublish_article_path(id: article), method: :put, data: { confirm: "Unpublish: #{article.title}" } %></li>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= "No published articles matching your search were found." if @articles.count === 0 %>

<%= paginate @articles %>

app/views/articles/show.html.erb
<% title "#{@article.title}" %>

<div class="row">
	<div class="col-md-9">
		<article>
			<h1><%= @article.title %></h1>
			<div class="article-content"><%= @article.content.html_safe %></div>
		</article>
	</div>
	<div class="col-md-3"></div>
</div>