config/routes.rb
Rails.application.routes.draw do

  # Resources
  resources :images, only: [:new, :create, :destroy]
  resources :articles do
    get 'published', on: :collection #view and scope
    put 'unpublish', on: :member # action
    post 'publish', on: :member # action
    get 'prepare_publish', on: :member # set tags and release date
  end

  # Devise
  devise_for :users

  as :user do
    get '/auth/login'          => "devise/sessions#new", as: :login
    post '/auth/login'          => "devise/sessions#create"
    get '/auth/logout'         => "devise/sessions#destroy", as: :logout
    get '/auth/reset_password' => "devise/passwords#new", as: :reset_password
    post '/auth/reset_password' => "devise/passwords#create"
    get '/auth/unlock_account' => "devise/unlocks#new", as: :unlock_account
    post '/auth/unlock_account' => "devise/unlocks#create"
  end

  authenticated :user do
    root to: 'articles#index', as: :authenticated_root
  end

  # App root
  root to: redirect('/auth/login')

end

app/views/shared/_editor_tags.html.erb
<div class="editor">
	<div class="btn-group btn-group-sm">
		<!-- Bold Italic Underline -->
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<strong> </strong>"><i class="fa fa-bold"></i></button>
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<em> </em>"><i class="fa fa-italic"></i></button>
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<u> </u>"><i class="fa fa-underline"></i></button>
	</div>

	<div class="btn-group btn-group-sm">
		<!--  Code Headings Quote -->
		<button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<code> </code>"><i class="fa fa-code"></i></button>
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<h1> </h1> [1-6]"><i class="fa fa-header"></i></button>
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<blockquote> </blockquote> [optional: <footer> </footer>]"><i class="fa fa-quote-right"></i></button>
	</div>	

	<div class="btn-group btn-group-sm">
		<!-- Lists -->
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<ul> <li></li> </ul>"><i class="fa fa-list"></i></button>
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<ol> <li></li> </ol>"><i class="fa fa-list-ol"></i></button>
	</div>

	<div class="btn-group btn-group-sm">
		<!-- Image and Link -->
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<div class='image'> <div class='wrap-img'> <img src='' alt=''> <figcaption>"><i class="fa fa-image"></i></button>
	  <button type="button" class="btn btn-default pop" data-container="body" data-toggle="popover" data-placement="top" data-content="<a href='http://'> </a>"><i class="fa fa-link"></i></button>
	</div>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert <%= bootstrap_class_for(flash_type) %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-default row">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" style="width: 100%;" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">Menu</button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="row">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul id="navigation" class="nav nav-pills">

          <!-- Main links -->
          <li class="<%= 'active' if params[:controller] === 'articles' && !current_page?(published_articles_path) %>"><%= link_to "Drafts", articles_path %></a></li>
          <li class="<%= 'active' if current_page?(published_articles_path) %>"><%= link_to "Published", published_articles_path %></a></li>
          <li class="<%= 'active' if params[:controller] === 'images' %>"><%= link_to 'Images', new_image_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Disqus</a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="https://productionqa.disqus.com/admin/moderate/" target="_blank">ProductionQA</a></li>
              <li><a href="https://sundaystruggle.disqus.com/admin/moderate/" target="_blank">SundayStruggle</a></li>
            </ul>
          </li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "secondary-link" %></li>

          <!-- Search -->
          <% if action_name === 'index' || action_name === 'published' %>
            <li id="search" class="pull-right">
              <% if action_name === 'index' %>
                <%= form_tag articles_path, method: :get do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
                <% end %>
              <% elsif action_name === 'published' %>
                <%= form_tag published_articles_path, method: :get do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
                <% end %>
              <% end %>        
            </li>
          <% end %>     

          <!-- Back button -->
          <% unless action_name === 'index' || action_name === 'published' || action_name === 'prepare_publish' || controller_name === 'images' || @article.errors.any? %>
            <li id="back" class="pull-right"><%= link_to 'Back', :back, class: 'btn btn-default' %></li>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
</div>